"""Generate statically bound resource WASM entry points from the IOA manifest."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parent
PROVIDERS = {
    "railway": "Railway",
    "vercel": "Vercel",
    "supabase": "Supabase",
    "r2": "R2",
    "datadog": "Datadog",
    "media": "Media",
}
ACTIONS = {
    "deploy": "Deploy",
    "configuration": "ApplyConfiguration",
    "rollback": "Rollback",
    "alias": "SetAlias",
    "retry_selected": "RetrySelected",
}
PHASES = {
    "validate": "Validation",
    "execute": "Execution",
    "observe": "Observation",
    "verify": "Verification",
}


def module_files(name: str) -> dict[Path, str]:
    """Return the complete entry point for a single provider action stage."""
    collect = re.fullmatch(r"dsf_([a-z0-9]+)_collect", name)
    if collect is not None and collect[1] in PROVIDERS:
        provider = PROVIDERS[collect[1]]
        manifest = f'''# Generated by wasm/generate_modules.py; edit the IOA manifest and generator.
[package]
name = "{name.replace("_", "-")}"
version = "0.1.0"
edition = "2024"
[workspace]
[lib]
crate-type = ["cdylib"]
[dependencies]
dsf-resource-collect = {{ path = "../dsf_resource_collect" }}
'''
        source = f"""//! Generated: observe one {provider} resource.
#[cfg(target_arch = "wasm32")]
#[unsafe(no_mangle)]
pub extern "C" fn run(_ctx_ptr: i32, _ctx_len: i32) -> i32 {{
    dsf_resource_collect::guest::run::<dsf_resource_collect::{provider}>()
}}
"""
        return {
            ROOT / name / "Cargo.toml": manifest,
            ROOT / name / "src/lib.rs": source,
        }
    match = re.fullmatch(
        r"dsf_([a-z0-9]+)_(deploy|configuration|rollback|alias|retry_selected)_(validate|execute|observe|verify)",
        name,
    )
    if match is None or match[1] not in PROVIDERS:
        raise ValueError(f"Unrecognized resource module: {name}")
    provider, action, phase = match.groups()
    crate = f"dsf_{provider}_actions"
    action_type = ACTIONS[action]
    package = name.replace("_", "-")
    path = ROOT / name
    manifest = f'''# Generated by wasm/generate_modules.py; edit the IOA manifest and generator.
[package]
name = "{package}"
version = "0.1.0"
edition = "2024"
[workspace]
[lib]
crate-type = ["cdylib"]
[dependencies]
dsf-resource-common = {{ path = "../dsf_resource_common" }}
{crate.replace("_", "-")} = {{ path = "../{crate}" }}
'''
    source = f"""//! Generated: {provider} {action_type}, {phase} stage only.
#[cfg(target_arch = "wasm32")]
#[unsafe(no_mangle)]
pub extern "C" fn run(_ctx_ptr: i32, _ctx_len: i32) -> i32 {{
    dsf_resource_common::guest::run::<{crate}::{action_type}>(
        dsf_resource_common::{phase}::<{crate}::{action_type}>,
        dsf_resource_common::guest::Failure::{PHASES[phase]},
    )
}}
"""
    return {path / "Cargo.toml": manifest, path / "src/lib.rs": source}


def expected_files() -> dict[Path, str]:
    """Read the authoritative resource manifest and all declared integrations."""
    manifest: object = json.loads(
        (ROOT.parent / "specs/module-contracts.json").read_text()
    )
    if not isinstance(manifest, dict) or not isinstance(
        manifest.get("resources"), dict
    ):
        raise TypeError("Module manifest requires resource definitions")
    files: dict[Path, str] = {}
    for resource in manifest["resources"].values():
        if not isinstance(resource, dict) or not isinstance(
            resource.get("modules"), dict
        ):
            raise TypeError("Resource definition requires modules")
        for name in resource["modules"]:
            if not isinstance(name, str):
                raise TypeError("Module names must be strings")
            for path, content in module_files(name).items():
                if path in files:
                    raise ValueError(f"Duplicate generated module path: {path}")
                files[path] = content
    declarations = declared_modules()
    generated = {path.parent.name for path in files if path.name == "Cargo.toml"}
    if not generated <= declarations:
        raise ValueError("Resource manifest contains modules absent from IOA triggers")
    app = """# Generated by wasm/generate_modules.py from the declared IOA triggers.
name = "dsf-factory"
description = "Deep Sci-fi operational resources, evidence, delivery and experiments"
version = "0.1.0"
dependencies = ["paw-patrol", "paw-compute"]
"""
    for name in sorted(declarations):
        app += f'\n[[wasm_modules]]\nname = "{name}"\ncriticality = "app-required"\nstartup_loading = "lazy"\n'
    files[ROOT.parent / "app.toml"] = app
    return files


def declared_modules() -> set[str]:
    """Module installation follows executable specs rather than a second list."""
    modules: set[str] = set()
    for spec in sorted((ROOT.parent / "specs").glob("*.ioa.toml")):
        data = tomllib.loads(spec.read_text())
        for action in data.get("action", []):
            for trigger in action.get("triggers", []):
                if trigger.get("kind") == "wasm":
                    name = trigger["module"]
                    if (
                        not isinstance(name, str)
                        or re.fullmatch(r"dsf_[a-z0-9_]+", name) is None
                    ):
                        raise ValueError(f"Invalid DSF module name in {spec.name}")
                    modules.add(name)
    return modules


def generate(*, check: bool) -> int:
    files = expected_files()
    stale = [
        path
        for path, content in files.items()
        if not path.is_file() or path.read_text() != content
    ]
    existing = {
        path
        for path in ROOT.glob("*/Cargo.toml")
        if path.read_text().startswith("# Generated by wasm/generate_modules.py")
    }
    unexpected = existing - files.keys()
    if unexpected:
        raise ValueError(
            f"Retired generated modules require removal: {sorted(map(str, unexpected))}"
        )
    if check and stale:
        raise ValueError(
            f"Generated module drift: {sorted(str(path.relative_to(ROOT)) for path in stale)}"
        )
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(files[path])
    return sum(path.name == "Cargo.toml" for path in files)


def build(names: list[str]) -> None:
    """Build and package selected declared modules using one local target cache."""
    modules = declared_modules()
    selected = names or sorted(modules)
    if any(name not in modules for name in selected):
        raise ValueError("Build selection contains an undeclared module")
    target = ROOT / "target"
    for name in selected:
        manifest = ROOT / name / "Cargo.toml"
        if not manifest.is_file():
            raise FileNotFoundError(f"Declared module has no source: {name}")
        subprocess.run(
            [
                "cargo",
                "build",
                "--manifest-path",
                str(manifest),
                "--target-dir",
                str(target),
                "--target",
                "wasm32-unknown-unknown",
                "--release",
            ],
            check=True,
        )
        artifact = target / "wasm32-unknown-unknown/release" / f"{name}.wasm"
        if artifact.read_bytes()[:8] != b"\0asm\x01\0\0\0":
            raise ValueError(f"Invalid WASM artifact: {name}")
        shutil.copyfile(artifact, ROOT / name / artifact.name)
        print(f"Packaged {name}", flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--build", action="store_true")
    parser.add_argument("--module", action="append", default=[])
    args = parser.parse_args()
    count = generate(check=args.check)
    print(
        f"{count} resource action WASM entry points {'verified' if args.check else 'generated'}"
    )
    if args.build:
        build(args.module)


if __name__ == "__main__":
    main()
