"""Render typed DSF contracts; run with --check to detect stale generated files."""

import argparse
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parent
# Each entry names a real provider object and only its supported mutations.
RESOURCES = {
    "railway_service_instance": (
        "DsfRailwayServiceInstance",
        "railway",
        ["project_id", "service_id", "environment_id"],
        {
            "Deploy": "deploy",
            "ApplyConfiguration": "configuration",
            "Rollback": "rollback",
        },
    ),
    "vercel_project": (
        "DsfVercelProject",
        "vercel",
        ["account_id", "project_id"],
        {
            "Deploy": "deploy",
            "ApplyConfiguration": "configuration",
            "Rollback": "rollback",
            "SetAlias": "alias",
        },
    ),
    "supabase_project": (
        "DsfSupabaseProject",
        "supabase",
        ["project_ref"],
        {"ApplyConfiguration": "configuration"},
    ),
    "cloudflare_r2_bucket": (
        "DsfCloudflareR2Bucket",
        "r2",
        ["account_id", "bucket_name"],
        {"ApplyConfiguration": "configuration"},
    ),
    "datadog_monitor": (
        "DsfDatadogMonitor",
        "datadog",
        ["site", "organization_id", "monitor_id"],
        {"ApplyConfiguration": "configuration"},
    ),
    "media_pipeline": (
        "DsfMediaPipeline",
        "media",
        ["application_id", "environment_id", "api_resource_id", "bucket_resource_id"],
        {"RetrySelected": "retry_selected"},
    ),
}


def inline(value):
    if isinstance(value, dict):
        return (
            "{ "
            + ", ".join(f"{key} = {inline(item)}" for key, item in value.items())
            + " }"
        )
    if isinstance(value, list):
        return "[" + ", ".join(inline(item) for item in value) + "]"
    return json.dumps(value)


def render(document):
    lines = [
        "# Generated by specs/generate.py; edit its resource manifest and render again."
    ]

    def table(name, value, array=False):
        lines.extend(["", f"[[{name}]]" if array else f"[{name}]"])
        for key, item in value.items():
            if isinstance(item, dict) or (
                isinstance(item, list)
                and item
                and isinstance(item[0], dict)
                and key in ("constraints", "triggers")
            ):
                continue
            lines.append(f"{key} = {inline(item)}")
        for key, item in value.items():
            if isinstance(item, dict):
                table(f"{name}.{key}", item)
            elif (
                isinstance(item, list)
                and item
                and isinstance(item[0], dict)
                and key in ("constraints", "triggers")
            ):
                for child in item:
                    table(f"{name}.{key}", child, True)

    for key, value in document.items():
        if isinstance(value, list):
            for item in value:
                table(key, item, True)
        else:
            table(key, value)
    return "\n".join(lines) + "\n"


def verification_flag(operation):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", operation).lower() + "_verified"


def field(name, kind="string", initial=None):
    return {
        "name": name,
        "type": kind,
        "initial": initial
        if initial is not None
        else {"string": "", "counter": "0", "bool": "false"}[kind],
    }


def params(names, counters=()):
    return [
        {"name": name, "type": "counter" if name in counters else "string"}
        for name in names
    ]


def nonempty(*names):
    return [{"kind": "param_nonempty", "param": name} for name in names]


def equals(param, field_name=None):
    return {"kind": "param_equals_field", "param": param, "field": field_name or param}


def action(
    name,
    before,
    after=None,
    inputs=(),
    constraints=(),
    effects=(),
    guards=(),
    counters=(),
    triggers=(),
):
    value = {
        "name": name,
        "kind": "input",
        "from": before,
        "params": params(inputs, counters),
    }
    if after:
        value["to"] = after
    if (
        any(item.get("param") == "expected_operation_sequence" for item in constraints)
        and "expected_operation_sequence" not in inputs
    ):
        value["params"].append(
            {"name": "expected_operation_sequence", "type": "counter"}
        )
    if constraints:
        value["constraints"] = list(constraints)
    if effects:
        value["effect"] = list(effects)
    if guards:
        value["guard"] = list(guards)
    if triggers:
        value["triggers"] = list(triggers)
    return value


def entity_trigger(
    name, entity, action_name, mapping=None, constants=None, resolver=None
):
    result = {
        "name": name,
        "kind": "entity",
        "principal": "dsf-factory-runtime",
        "target_entity": entity,
        "target_action": action_name,
        "resolve_target": resolver or {"type": "same_id"},
    }
    if mapping:
        result["params_from"] = mapping
    if constants:
        result["params"] = constants
    return result


def wasm(module, failure):
    return {
        "name": module,
        "kind": "wasm",
        "module": module,
        "config": {
            "timeout_secs": "240"
            if module.startswith("dsf_media_retry_selected_")
            else "120",
        },
    }


def assign(name):
    return {"type": "set_counter_from_param", "var": name, "param": name}


def increment(name):
    return {"type": "increment", "var": name}


def bounded(name, maximum):
    return {"type": "max_count", "var": name, "max": maximum}


EVIDENCE = [
    "observation_id",
    "source_event_id",
    "query",
    "window_start",
    "window_end",
    "sample_kind",
    "outcome",
    "summary",
    "evidence_ref",
    "observed_at_ms",
    "expected_resource_sequence",
]
OBSERVED = ["observed_configuration", "observed_revision"]
COUNTERS = [
    "model_sequence",
    "observed_sequence",
    "observed_at_ms",
    "operation_sequence",
    "execution_attempts",
    "reconciliation_attempts",
    "verification_attempts",
    "refresh_sequence",
    "collected_observed_at_ms",
    "collected_expected_resource_sequence",
]
REQUEST = [
    "operation_key",
    "expected_operation_sequence",
    "effort_id",
    "request_revision",
    "request_configuration",
    "proof_ref",
]


def resource_document(entity, provider, identity, operations):
    stages = [
        "Validating",
        "Ready",
        "Executing",
        "Unknown",
        "Reconciling",
        "Observed",
        "Verifying",
        "Blocked",
        "Failed",
    ]
    states = ["Draft", "Active", "Refreshing", "Retired"] + [
        operation + stage for operation in operations for stage in stages
    ]
    fields = (
        identity
        + [
            "name",
            "application_id",
            "environment_name",
            "source_repository",
            "config_ref",
            "config_sha256",
            "allowed_operations",
            "dependency_ids",
            "model_provenance_ref",
            "intended_configuration",
            "intended_revision",
            "operation_key",
            "effort_id",
            "request_revision",
            "request_configuration",
            "proof_ref",
            "validation_evidence_ref",
            "provider_execution_id",
            "provider_evidence_ref",
            "absence_evidence_ref",
            "flow_evidence_ref",
            "telemetry_evidence_ref",
            "error_message",
            "ask_id",
        ]
        + ["collected_" + name for name in EVIDENCE + OBSERVED]
        + OBSERVED
        + ["observation_id"]
    )
    if provider == "vercel":
        fields += ["deployment_target", "alias"]
    if "Rollback" in operations:
        fields.append("rollback_execution_id")
    if "RetrySelected" in operations:
        fields += ["selected_generation_ids", "cost_authority_ref"]
    fields = [name for name in dict.fromkeys(fields) if name not in COUNTERS]
    doc = {
        "automaton": {
            "name": entity,
            "states": states,
            "initial": "Draft",
            "strict_action_params": True,
            "allow_indefinite_states": [
                state for state in states if state != "Retired"
            ],
        },
        "state": [field(name) for name in fields]
        + [field(name, "counter") for name in COUNTERS]
        + [
            field("observation_available", "bool"),
            field("provider_known", "bool"),
            field("operation_verified", "bool"),
        ]
        + [field(verification_flag(operation), "bool") for operation in operations],
        "action": [],
        "state_timeout": [
            {
                "state": "Active",
                "after_seconds": 300,
                "on_timeout": "RefreshObservations",
            }
        ],
        "invariant": [],
    }
    actions = doc["action"]
    register = list(
        dict.fromkeys(
            identity
            + [
                "name",
                "application_id",
                "environment_name",
                "source_repository",
                "config_ref",
                "config_sha256",
                "allowed_operations",
                "dependency_ids",
                "intended_configuration",
            ]
        )
    )
    actions.append(
        action(
            "Register",
            ["Draft"],
            "Active",
            register,
            nonempty(*identity, "config_ref", "config_sha256"),
        )
    )
    actions.append(model_revision(operations))
    live = [state for state in states if state not in ("Draft", "Retired")]
    observation_inputs = [
        "observation_id",
        "coverage",
        "outcome",
        "provenance_ref",
        "observed_at_ms",
        "expected_sequence",
    ]
    doc["state"] += [field("coverage"), field("provenance_ref")]
    for unavailable in (False, True):
        inputs = observation_inputs + ([] if unavailable else OBSERVED)
        actions.append(
            action(
                "ObserveUnavailable" if unavailable else "Observe",
                live,
                inputs=inputs,
                counters=["observed_at_ms", "expected_sequence"],
                constraints=[
                    equals("expected_sequence", "observed_sequence"),
                    {
                        "kind": "param_greater_than_field",
                        "param": "observed_at_ms",
                        "field": "observed_at_ms",
                    },
                ]
                + nonempty("observation_id", "coverage", "provenance_ref"),
                effects=[
                    increment("observed_sequence"),
                    assign("observed_at_ms"),
                    {
                        "type": "set_bool",
                        "var": "observation_available",
                        "value": not unavailable,
                    },
                ],
            )
        )
    module = f"dsf_{provider}_collect"
    actions.append(
        action(
            "RefreshObservations",
            ["Active"],
            "Refreshing",
            effects=[
                increment("refresh_sequence"),
                {"type": "trigger", "name": module},
            ],
            triggers=[wasm(module, "CollectionFailed")],
        )
    )
    actions.append(
        action(
            "CollectionFailed",
            ["Refreshing"],
            "Active",
            ["error_message", "expected_refresh_sequence"],
            [equals("expected_refresh_sequence", "refresh_sequence")],
            counters=["expected_refresh_sequence"],
        )
    )
    actions.append(action("CollectionTimedOut", ["Refreshing"], "Active"))
    doc["state_timeout"].append(
        {
            "state": "Refreshing",
            "after_seconds": 300,
            "on_timeout": "CollectionTimedOut",
        }
    )
    for coverage in ["Measured", "Absent", "Inaccessible", "Stale"]:
        inputs = ["expected_refresh_sequence", "error_message"] + [
            "collected_" + name
            for name in EVIDENCE + (OBSERVED if coverage == "Measured" else [])
        ]
        mapping = {
            name: "collected_" + name for name in EVIDENCE if name != "observation_id"
        }
        mapping.update(subject_id="Id", source="config_ref")
        if coverage == "Measured":
            mapping.update({name: "collected_" + name for name in OBSERVED})
        trigger = entity_trigger(
            "record_" + coverage.lower(),
            "DsfObservation",
            f"Record{entity[3:]}{coverage}",
            mapping,
            {"subject_type": entity},
            {"type": "create_if_missing", "id_field": "collected_observation_id"},
        )
        actions.append(
            action(
                "Collection" + coverage,
                ["Refreshing"],
                "Active",
                inputs,
                [equals("expected_refresh_sequence", "refresh_sequence")]
                + nonempty(
                    *[
                        "collected_" + name
                        for name in [
                            "observation_id",
                            "source_event_id",
                            "window_start",
                            "window_end",
                            "evidence_ref",
                        ]
                    ]
                ),
                [
                    assign("collected_observed_at_ms"),
                    assign("collected_expected_resource_sequence"),
                ],
                counters=[
                    "expected_refresh_sequence",
                    "collected_observed_at_ms",
                    "collected_expected_resource_sequence",
                ],
                triggers=[trigger],
            )
        )
    for operation, concern in operations.items():
        make_operation(doc, entity, provider, operation, concern)
    actions.append(
        action("Retire", ["Active"], "Retired", ["effort_id"], nonempty("effort_id"))
    )
    doc["invariant"] += [
        {
            "name": "RetiredIsFinal",
            "when": ["Retired"],
            "assert": "no_further_transitions",
        },
        {"name": "BoundedWrites", "assert": "execution_attempts <= 3"},
        {"name": "BoundedReconciliation", "assert": "reconciliation_attempts <= 20"},
        {"name": "BoundedVerification", "assert": "verification_attempts <= 40"},
    ]
    return doc


def model_revision(operations: dict[str, str]) -> dict:
    """Declare graph maintenance without a provider write or identity change."""
    return action(
        "ReviseModel",
        ["Active"],
        inputs=[
            "expected_model_sequence",
            "name",
            "source_repository",
            "dependency_ids",
            "config_ref",
            "config_sha256",
            "allowed_operations",
            "model_provenance_ref",
        ],
        constraints=[equals("expected_model_sequence", "model_sequence")]
        + nonempty("config_ref", "config_sha256", "model_provenance_ref"),
        effects=[
            increment("model_sequence"),
            {"type": "set_bool", "var": "operation_verified", "value": False},
        ]
        + [
            {"type": "set_bool", "var": verification_flag(operation), "value": False}
            for operation in operations
        ],
        counters=["expected_model_sequence"],
    )


def make_operation(doc, entity, provider, operation, concern):
    actions = doc["action"]

    def state(stage):
        return operation + stage

    def continuation(stage):
        return entity_trigger("continue_" + stage.lower(), entity, operation + stage)

    def integrate(stage, before, after, failure, guards=(), effects=()):
        module = f"dsf_{provider}_{concern}_{stage.lower()}"
        actions.append(
            action(
                operation + stage,
                [state(before)],
                state(after),
                effects=list(effects) + [{"type": "trigger", "name": module}],
                guards=guards,
                triggers=[wasm(module, operation + failure)],
            )
        )

    request = list(REQUEST)
    if provider == "vercel":
        request.append("deployment_target")
    if operation == "Rollback":
        request.append("rollback_execution_id")
    if operation == "SetAlias":
        request += ["alias", "provider_execution_id"]
    if operation == "RetrySelected":
        request += ["selected_generation_ids", "cost_authority_ref"]
    required = ["operation_key", "effort_id", "proof_ref", "request_configuration"] + (
        ["request_configuration"]
        if operation in ("ApplyConfiguration", "SetAlias")
        else ["request_revision"]
    )
    if operation == "RetrySelected":
        required.append("selected_generation_ids")
    if operation == "Rollback":
        required.append("rollback_execution_id")
    if provider == "vercel":
        required.append("deployment_target")
    if operation == "SetAlias":
        required += ["alias", "provider_execution_id"]
    reset = [
        increment("operation_sequence"),
        {"type": "set_bool", "var": "provider_known", "value": False},
        {"type": "set_bool", "var": "operation_verified", "value": False},
    ]
    reset += [
        {"type": "set_bool", "var": variable["name"], "value": False}
        for variable in doc["state"]
        if variable["type"] == "bool"
        and variable["name"].endswith("_verified")
        and variable["name"] != "operation_verified"
    ]
    reset += [
        {"type": "decrement", "var": counter}
        for counter, maximum in [
            ("execution_attempts", 3),
            ("reconciliation_attempts", 20),
            ("verification_attempts", 40),
        ]
        for _ in range(maximum)
    ]
    module = f"dsf_{provider}_{concern}_validate"
    actions.append(
        action(
            operation,
            ["Active"],
            state("Validating"),
            request,
            [equals("expected_operation_sequence", "operation_sequence")]
            + nonempty(*required),
            reset + [{"type": "trigger", "name": module}],
            counters=["expected_operation_sequence"],
            triggers=[wasm(module, operation + "ValidationFailed")],
        )
    )
    correlation = [
        equals("operation_key"),
        equals("expected_operation_sequence", "operation_sequence"),
    ]
    intended = (
        "intended_configuration"
        if operation in ("ApplyConfiguration", "SetAlias")
        else "intended_revision"
    )
    requested_intent = (
        "request_configuration"
        if intended == "intended_configuration"
        else "request_revision"
    )
    actions.append(
        action(
            operation + "ValidationSucceeded",
            [state("Validating")],
            state("Ready"),
            ["operation_key", "validation_evidence_ref", intended],
            correlation
            + [equals(intended, requested_intent)]
            + nonempty("validation_evidence_ref"),
            triggers=[continuation("Execute")],
        )
    )
    actions.append(
        action(
            operation + "ValidationBlocked",
            [state("Validating")],
            state("Blocked"),
            ["operation_key", "ask_id", "error_message"],
            correlation + nonempty("ask_id", "error_message"),
        )
    )
    actions.append(
        action(
            operation + "ValidationFailed",
            [state("Validating")],
            state("Failed"),
            ["operation_key", "error_message"],
            correlation,
        )
    )
    # A failed validation may be retried only against the same accepted request.
    integrate("Validate", "Blocked", "Validating", "ValidationFailed")
    integrate(
        "Execute",
        "Ready",
        "Executing",
        "ExecutionUncertain",
        [
            bounded("execution_attempts", 3),
            {"type": "is_false", "var": "provider_known"},
        ],
        [increment("execution_attempts")],
    )
    provider_inputs = [
        "operation_key",
        "provider_execution_id",
        "provider_evidence_ref",
    ]
    provider_constraints = correlation + nonempty(
        "provider_execution_id", "provider_evidence_ref"
    )
    known = [{"type": "set_bool", "var": "provider_known", "value": True}]
    actions.append(
        action(
            operation + "ExecutionSucceeded",
            [state("Executing")],
            state("Observed"),
            provider_inputs,
            provider_constraints,
            known,
            triggers=[continuation("Verify")],
        )
    )
    actions.append(
        action(
            operation + "ExecutionUncertain",
            [state("Executing")],
            state("Unknown"),
            ["operation_key", "error_message"],
            correlation,
        )
    )
    integrate(
        "Reconcile",
        "Unknown",
        "Reconciling",
        "ObservationFailed",
        [bounded("reconciliation_attempts", 20)],
        [increment("reconciliation_attempts")],
    )
    # The integration concern is a provider read, independent of the action name.
    reconcile = actions[-1]
    reconcile["triggers"][0]["module"] = f"dsf_{provider}_{concern}_observe"
    reconcile["triggers"][0]["name"] = f"dsf_{provider}_{concern}_observe"
    reconcile["effect"][-1]["name"] = f"dsf_{provider}_{concern}_observe"
    actions.append(
        action(
            operation + "ProviderFound",
            [state("Reconciling")],
            state("Observed"),
            provider_inputs,
            provider_constraints,
            known,
            triggers=[continuation("Verify")],
        )
    )
    actions.append(
        action(
            operation + "ProviderAbsent",
            [state("Reconciling")],
            state("Ready"),
            ["operation_key", "absence_evidence_ref"],
            correlation + nonempty("absence_evidence_ref"),
            guards=[
                bounded("execution_attempts", 3),
                {"type": "is_false", "var": "provider_known"},
            ],
            triggers=[continuation("Execute")],
        )
    )
    actions.append(
        action(
            operation + "ObservationFailed",
            [state("Reconciling")],
            state("Unknown"),
            ["operation_key", "error_message"],
            correlation,
        )
    )
    integrate(
        "Verify",
        "Observed",
        "Verifying",
        "VerificationPending",
        [
            bounded("verification_attempts", 40),
            {"type": "is_true", "var": "provider_known"},
        ],
        [increment("verification_attempts")],
    )
    binding = (
        "verified_configuration"
        if operation in ("ApplyConfiguration", "SetAlias")
        else "verified_revision"
    )
    requested = (
        "request_configuration"
        if binding == "verified_configuration"
        else "request_revision"
    )
    success_inputs = [
        "operation_key",
        "verified_resource_id",
        binding,
        "provider_evidence_ref",
        "flow_evidence_ref",
        "telemetry_evidence_ref",
    ]
    actions.append(
        action(
            operation + "VerificationSucceeded",
            [state("Verifying")],
            "Active",
            success_inputs,
            correlation
            + [equals("verified_resource_id", "Id"), equals(binding, requested)]
            + nonempty(
                "provider_evidence_ref", "flow_evidence_ref", "telemetry_evidence_ref"
            ),
            [
                {"type": "set_bool", "var": "operation_verified", "value": True},
                {
                    "type": "set_bool",
                    "var": verification_flag(operation),
                    "value": True,
                },
            ],
        )
    )
    actions.append(
        action(
            operation + "VerificationPending",
            [state("Verifying")],
            state("Observed"),
            ["operation_key", "error_message"],
            correlation,
        )
    )
    actions.append(
        action(
            operation + "VerificationFailed",
            [state("Verifying")],
            state("Failed"),
            ["operation_key", "error_message"],
            correlation + nonempty("error_message"),
        )
    )
    actions.append(
        action(
            operation + "AcknowledgeFailure",
            [state("Failed")],
            "Active",
            ["operation_key", "failure_evidence_ref"],
            correlation + nonempty("failure_evidence_ref"),
        )
    )
    # Explicit recovery resets only reads; it cannot create another provider write.
    for suffix, before, counter, maximum, next_action in [
        ("ResumeReconciliation", "Unknown", "reconciliation_attempts", 20, "Reconcile"),
        ("ResumeVerification", "Observed", "verification_attempts", 40, "Verify"),
    ]:
        actions.append(
            action(
                operation + suffix,
                [state(before)],
                state(before),
                ["operation_key"],
                correlation,
                [{"type": "decrement", "var": counter} for _ in range(maximum)],
                triggers=[continuation(next_action)],
            )
        )
    # Unknown and pending states retain resource ownership after bounded retries.
    for stage, seconds, callback, maximum in [
        ("Validating", 300, "ValidationFailed", 1),
        ("Executing", 300, "ExecutionUncertain", 3),
        ("Unknown", 30, "Reconcile", 20),
        ("Reconciling", 300, "ObservationFailed", 20),
        ("Observed", 30, "Verify", 40),
        ("Verifying", 300, "VerificationPending", 40),
    ]:
        if stage in ("Unknown", "Observed"):
            timeout_action = operation + callback
        else:
            timeout_action = operation + stage + "TimedOut"
            destination = {
                "Validating": "Failed",
                "Executing": "Unknown",
                "Reconciling": "Unknown",
                "Verifying": "Observed",
            }[stage]
            actions.append(action(timeout_action, [state(stage)], state(destination)))
        doc["state_timeout"].append(
            {
                "state": state(stage),
                "after_seconds": seconds,
                "on_timeout": timeout_action,
                "max_occurrences": maximum,
            }
        )


def observation_document():
    doc = tomllib.loads((ROOT / "observation.base.toml").read_text())
    templates = [
        item for item in doc["action"] if item["name"].startswith("RecordResource")
    ]
    doc["action"] = [
        item for item in doc["action"] if not item["name"].startswith("RecordResource")
    ]
    for entity, _, _, _ in RESOURCES.values():
        for template in templates:
            item = json.loads(json.dumps(template))
            item["name"] = item["name"].replace("Resource", entity[3:])
            item["triggers"][0]["target_entity"] = entity
            item["triggers"][0]["principal"] = "dsf-factory-runtime"
            doc["action"].append(item)
    return doc


def sync_document():
    doc = tomllib.loads((ROOT / "model_sync.base.toml").read_text())
    for item in doc["action"]:
        for trigger in item.get("triggers", []):
            if trigger.get("target_entity") == "DsfObservation":
                trigger["principal"] = "dsf-factory-runtime"
                trigger["params"] = {}
                trigger["params_from"]["subject_type"] = "subject_type"
                for name in [
                    "expected_resource_sequence",
                    "observed_configuration",
                    "observed_revision",
                ]:
                    trigger["params_from"].pop(name, None)
    doc["state"].append(field("subject_type"))
    configure = next(item for item in doc["action"] if item["name"] == "Configure")
    configure["params"].append({"name": "subject_type", "type": "string"})
    configure["constraints"] += nonempty("subject_type")
    return doc


def csdl(documents):
    edm = "http://docs.oasis-open.org/odata/ns/edm"
    edmx = "http://docs.oasis-open.org/odata/ns/edmx"
    ET.register_namespace("edmx", edmx)
    ET.register_namespace("", edm)
    root = ET.Element(f"{{{edmx}}}Edmx", Version="4.0")
    schema = ET.SubElement(
        ET.SubElement(root, f"{{{edmx}}}DataServices"),
        f"{{{edm}}}Schema",
        Namespace="Dsf.Factory",
    )
    kinds = {"string": "Edm.String", "counter": "Edm.Int64", "bool": "Edm.Boolean"}

    def add(parent, tag, **attrs):
        return ET.SubElement(parent, f"{{{edm}}}{tag}", attrs)

    for document in documents:
        name = document["automaton"]["name"]
        entity = add(schema, "EntityType", Name=name)
        add(add(entity, "Key"), "PropertyRef", Name="Id")
        add(entity, "Property", Name="Id", Type="Edm.String", Nullable="false")
        add(entity, "Property", Name="Status", Type="Edm.String")
        for variable in document.get("state", []):
            add(
                entity,
                "Property",
                Name="".join(part.capitalize() for part in variable["name"].split("_")),
                Type=kinds[variable["type"]],
            )
        for operation in document["action"]:
            bound = add(schema, "Action", Name=operation["name"], IsBound="true")
            add(bound, "Parameter", Name="bindingParameter", Type=f"Dsf.Factory.{name}")
            for parameter in operation.get("params", []):
                add(
                    bound,
                    "Parameter",
                    Name=parameter["name"],
                    Type=kinds[parameter["type"]],
                )
    container = add(schema, "EntityContainer", Name="Container")
    for document in documents:
        name = document["automaton"]["name"]
        add(container, "EntitySet", Name=name + "s", EntityType=f"Dsf.Factory.{name}")
    ET.indent(root, space="  ")
    return ET.tostring(root, encoding="unicode", xml_declaration=True) + "\n"


def module_manifest(documents):
    """Share callback shapes while retaining exact per-resource module bindings."""
    result = {"callback_shapes": {}, "resources": {}}
    shapes = result["callback_shapes"]
    for document in documents:
        entity = document["automaton"]["name"]
        actions = {entry["name"]: entry for entry in document["action"]}
        resource = {
            "entity_set": entity + "s",
            "register": actions["Register"]["params"],
            "properties": {"Id": "Edm.String", "Status": "Edm.String"},
            "human_actions": {},
            "verification_flags": {
                name.removesuffix("VerificationSucceeded"): verification_flag(
                    name.removesuffix("VerificationSucceeded")
                )
                for name in actions
                if name.endswith("VerificationSucceeded")
            },
            "modules": {},
        }
        kinds = {"string": "Edm.String", "counter": "Edm.Int64", "bool": "Edm.Boolean"}
        resource["properties"].update(
            {
                "".join(
                    part.capitalize() for part in variable["name"].split("_")
                ): kinds[variable["type"]]
                for variable in document.get("state", [])
            }
        )
        for name, entry in actions.items():
            if name in {
                "ReviseModel",
                "RefreshObservations",
                "Deploy",
                "ApplyConfiguration",
                "Rollback",
                "SetAlias",
                "RetrySelected",
            } or name.endswith(
                ("ResumeReconciliation", "ResumeVerification", "AcknowledgeFailure")
            ):
                resource["human_actions"][name] = {
                    "params": entry.get("params", []),
                    "from": entry["from"],
                    "param_nonempty": [
                        constraint["param"]
                        for constraint in entry.get("constraints", [])
                        if constraint["kind"] == "param_nonempty"
                    ],
                }
        for entry in document["action"]:
            for trigger in entry.get("triggers", []):
                if trigger["kind"] != "wasm":
                    continue
                name = entry["name"]
                if name == "RefreshObservations":
                    callback_names = [
                        "Collection" + coverage
                        for coverage in [
                            "Measured",
                            "Absent",
                            "Inaccessible",
                            "Stale",
                            "Failed",
                        ]
                    ]
                else:
                    phase = next(
                        (
                            phase
                            for phase in ["Execute", "Reconcile", "Verify", "Validate"]
                            if name.endswith(phase)
                        ),
                        "Request",
                    )
                    operation = name[: -len(phase)] if phase != "Request" else name
                    endings = {
                        "Request": [
                            "ValidationSucceeded",
                            "ValidationBlocked",
                            "ValidationFailed",
                        ],
                        "Validate": [
                            "ValidationSucceeded",
                            "ValidationBlocked",
                            "ValidationFailed",
                        ],
                        "Execute": ["ExecutionSucceeded", "ExecutionUncertain"],
                        "Reconcile": [
                            "ProviderFound",
                            "ProviderAbsent",
                            "ObservationFailed",
                        ],
                        "Verify": [
                            "VerificationSucceeded",
                            "VerificationPending",
                            "VerificationFailed",
                        ],
                    }[phase]
                    callback_names = [operation + ending for ending in endings]
                callbacks = {}
                for callback in callback_names:
                    shape = {
                        parameter["name"]: parameter["type"]
                        for parameter in actions[callback]["params"]
                    }
                    existing = next(
                        (key for key, value in shapes.items() if value == shape), None
                    )
                    if existing is None:
                        existing = f"shape_{len(shapes) + 1}"
                        shapes[existing] = shape
                    callbacks[callback] = existing
                resource["modules"][trigger["module"]] = {
                    "action": name,
                    "params": entry["params"],
                    "callbacks": callbacks,
                }
        result["resources"][entity] = resource
    return json.dumps(result, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = {
        filename: resource_document(*config) for filename, config in RESOURCES.items()
    }
    generated["observation"] = observation_document()
    generated["model_sync"] = sync_document()
    all_docs = list(generated.values()) + [
        tomllib.loads((ROOT / f"{name}.ioa.toml").read_text())
        for name in ["flow", "participant", "experiment"]
    ]
    outputs = {
        ROOT / f"{name}.ioa.toml": render(document)
        for name, document in generated.items()
    }
    outputs[ROOT / "model.csdl.xml"] = csdl(all_docs)
    outputs[ROOT / "module-contracts.json"] = module_manifest(
        list(generated.values())[: len(RESOURCES)]
    )
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale generated contract: {path.name}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
