"""Render exact DSF command and callback permissions from installed IOA contracts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import tomllib

APP = Path(__file__).resolve().parents[1]
MEMBER = '(principal has agent_type && principal has agentTypeVerified && principal.agentTypeVerified == true && ["dsf-factory", "human"].contains(principal.agent_type))'
RUNTIME = '(principal is System || (principal has role && principal.role == "service" && principal has agent_type && ["wasm-runtime", "dsf-factory-runtime", "timeout-scheduler"].contains(principal.agent_type)))'
HUMAN = {
    "DsfFlow": {"Register", "Revise", "Retire"},
    "DsfParticipant": {"RegisterAgent", "RegisterCohort", "ObserveActivity", "Retire"},
    "DsfObservation": set(),
    "DsfModelSync": {"Configure", "Refresh", "Pause", "Resume"},
    "DsfExperiment": {
        "Configure",
        "Validate",
        "ResumeValidation",
        "Run",
        "ResumeRun",
        "Cleanup",
        "ResumeCleanup",
        "Select",
        "ResumeSelection",
    },
}


def actions(names: set[str]) -> str:
    return (
        "[" + ", ".join(f"Action::{json.dumps(name)}" for name in sorted(names)) + "]"
    )


def render() -> str:
    manifest = json.loads((APP / "specs/module-contracts.json").read_text())
    commands = {key: set(value) for key, value in HUMAN.items()}
    for entity, resource in manifest["resources"].items():
        commands[entity] = set(resource["human_actions"]) | {"Register", "Retire"}
    docs = {}
    for path in sorted((APP / "specs").glob("*.ioa.toml")):
        doc = tomllib.loads(path.read_text())
        docs[doc["automaton"]["name"]] = doc
    if set(docs) != set(commands):
        raise ValueError(f"Unclassified entity types: {set(docs) ^ set(commands)}")
    rules = [
        "// Generated by policies/generate.py. Do not edit callback allowlists by hand."
    ]
    for entity, doc in sorted(docs.items()):
        declared = {action["name"] for action in doc["action"]}
        if not commands[entity] <= declared:
            raise ValueError(
                f"{entity}: missing commands {commands[entity] - declared}"
            )
        callbacks = declared - commands[entity]
        reads = {"read", "list"}
        human = commands[entity] | reads
        runtime = callbacks | reads
        if entity != "DsfObservation":
            human.add("create")
        else:
            callbacks.add("create")
            runtime.add("create")
        # Only declared timer actions receive scheduler authority.
        runtime |= {timer["on_timeout"] for timer in doc.get("state_timeout", [])}
        rules.append(
            f"permit(principal, action in {actions(human)}, resource is {entity}) when {{ {MEMBER} }};"
        )
        rules.append(
            f"permit(principal, action in {actions(runtime)}, resource is {entity}) when {{ {RUNTIME} }};"
        )
        if callbacks:
            rules.append(
                f"forbid(principal, action in {actions(callbacks)}, resource is {entity}) unless {{ {RUNTIME} }};"
            )
    rules.append("""permit(principal, action in [Action::"create", Action::"Run"], resource is Exec) when {
  principal has role && principal.role == "service" &&
  principal has agent_type && principal.agent_type == "dsf-factory-runtime" &&
  context has triggerDeclaredPrincipal && context.triggerDeclaredPrincipal == true &&
  context has triggerSourceEntityType && context.triggerSourceEntityType == "DsfExperiment"
};""")
    provider_secrets = {
        "railway": {"dsf_railway_token"},
        "vercel": {"dsf_vercel_token"},
        "supabase": {"dsf_supabase_token"},
        "r2": {"dsf_cloudflare_token"},
        "datadog": {"dsf_datadog_api_key", "dsf_datadog_app_key"},
        "media": {"dsf_admin_api_key", "dsf_railway_token", "dsf_cloudflare_token"},
    }
    telemetry = {"dsf_datadog_api_key", "dsf_datadog_app_key", "dsf_admin_api_key"}
    modules = tomllib.loads((APP / "app.toml").read_text())["wasm_modules"]
    for item in modules:
        module = item["name"]
        secrets = set()
        if module == "dsf_model_collect":
            secrets |= telemetry | {"dsf_github_token"}
        elif module.startswith("dsf_experiment_"):
            pass
        else:
            provider = module.split("_")[1]
            secrets |= provider_secrets[provider]
            if module.endswith("_verify"):
                secrets |= telemetry
            if provider != "vercel" and module.endswith("_configuration_verify"):
                secrets.add("dsf_railway_token")
        secret_ids = json.dumps(sorted(secrets))
        rules.append(
            f'permit(principal, action == Action::"access_secret", resource is Secret) when {{ principal has role && principal.role == "wasm_module" && context has module && context.module == "{module}" && {secret_ids}.contains(resource.id) }};'
        )
        rules.append(
            f'forbid(principal, action == Action::"access_secret", resource is Secret) when {{ context has module && context.module == "{module}" }} unless {{ {secret_ids}.contains(resource.id) }};'
        )
        # Each compiled module constrains its own provider URL, method and payload.
        # This grants host I/O only to that module, never a credentialed caller.
        rules.append(
            f'permit(principal, action == Action::"http_call", resource is HttpEndpoint) when {{ principal has role && principal.role == "wasm_module" && context has module && context.module == "{module}" }};'
        )
    return "\n\n".join(rules) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = APP / "policies/factory.cedar"
    rendered = render()
    if args.check:
        if not output.exists() or output.read_text() != rendered:
            raise SystemExit(
                "DSF policy differs from declared actions; run policies/generate.py"
            )
    else:
        output.write_text(rendered)


if __name__ == "__main__":
    main()
